// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe4_bVksDdMsvb28SAmpHSr8EF1o2j4uo',
    appId: '1:1085979298351:web:d31eaf472cfa04f24014da',
    messagingSenderId: '1085979298351',
    projectId: 'bd-accesscontrol',
    authDomain: 'bd-accesscontrol.firebaseapp.com',
    storageBucket: 'bd-accesscontrol.firebasestorage.app',
    measurementId: 'G-12NEBRSHV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8JILWwFPOoC6zCoLdbxrSUubTpVPt5I8',
    appId: '1:1085979298351:android:58a6b13a1182a7794014da',
    messagingSenderId: '1085979298351',
    projectId: 'bd-accesscontrol',
    storageBucket: 'bd-accesscontrol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB8cSCw7zDdivDqqUb2Mw8z2EHmgILCS0',
    appId: '1:1085979298351:ios:6bd86ac91b3884a44014da',
    messagingSenderId: '1085979298351',
    projectId: 'bd-accesscontrol',
    storageBucket: 'bd-accesscontrol.firebasestorage.app',
    iosBundleId: 'com.example.accesscontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB8cSCw7zDdivDqqUb2Mw8z2EHmgILCS0',
    appId: '1:1085979298351:ios:6bd86ac91b3884a44014da',
    messagingSenderId: '1085979298351',
    projectId: 'bd-accesscontrol',
    storageBucket: 'bd-accesscontrol.firebasestorage.app',
    iosBundleId: 'com.example.accesscontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe4_bVksDdMsvb28SAmpHSr8EF1o2j4uo',
    appId: '1:1085979298351:web:8269553ed57f3c6c4014da',
    messagingSenderId: '1085979298351',
    projectId: 'bd-accesscontrol',
    authDomain: 'bd-accesscontrol.firebaseapp.com',
    storageBucket: 'bd-accesscontrol.firebasestorage.app',
    measurementId: 'G-QQ4J8GDK0X',
  );

}